Fix metadata timestamp conversion
hyparam/hyparquet pull request #45
Opened 2024-11-23 10:00 UTC by cbardasano

Reading metadata fails if the units of the timestamp are nanosecods. This PR fixes this.

2024-11-25 17:26 UTC, platypii requested changes
Thanks! Looks good. One minor change please.

Also do you have an example file that uses micros or nanos?

2024-11-25 17:26 UTC, platypii commented on src/metadata.js
> +  if (type === 'INT64' && logical_type?.type === 'TIMESTAMP' && logical_type?.unit === 'MILLIS') return new Date(Number(view.getBigInt64(0, true)))
This last condition for `unit === 'MILLIS'` is not necessary because it's the same parsing as the next line.
```suggestion
```

2024-11-29 19:49 UTC, cbardasano commented
I'm sorry, but I can't send you an example file because the one I have contains private data and I only read it, I don't know how it is generated.

If it helps you, this is the metadata schema:

```
    "schema": [
      {
        "repetition_type": "REQUIRED",
        "name": "schema",
        "num_children": 12
      },
      {
        "type": "INT64",
        "repetition_type": "OPTIONAL",
        "name": "valueid"
      },
      {
        "type": "INT64",
        "repetition_type": "OPTIONAL",
        "name": "tileid"
      },
      {
        "type": "INT64",
        "repetition_type": "OPTIONAL",
        "name": "time",
        "logical_type": {
          "type": "TIMESTAMP",
          "isAdjustedToUTC": true,
          "unit": "NANOS"
        }
      },
      {
        "type": "INT64",
        "repetition_type": "OPTIONAL",
        "name": "expirationtime",
        "logical_type": {
          "type": "TIMESTAMP",
          "isAdjustedToUTC": true,
          "unit": "NANOS"
        }
      },
      {
        "type": "BYTE_ARRAY",
        "repetition_type": "OPTIONAL",
        "name": "sub_linkid",
        "converted_type": "UTF8",
        "logical_type": {
          "type": "STRING"
        }
      },
      {
        "type": "DOUBLE",
        "repetition_type": "OPTIONAL",
        "name": "Friction-Average"
      },
      {
        "type": "DOUBLE",
        "repetition_type": "OPTIONAL",
        "name": "Friction-Average-StandardDeviation"
      },
      {
        "type": "DOUBLE",
        "repetition_type": "OPTIONAL",
        "name": "Friction-Max"
      },
      {
        "type": "DOUBLE",
        "repetition_type": "OPTIONAL",
        "name": "Friction-Min"
      },
      {
        "type": "DOUBLE",
        "repetition_type": "OPTIONAL",
        "name": "HighestTGPWeight"
      },
      {
        "type": "DOUBLE",
        "repetition_type": "OPTIONAL",
        "name": "NumberOfTGPs"
      },
      {
        "type": "DOUBLE",
        "repetition_type": "OPTIONAL",
        "name": "Confidence"
      }
    ],
```

2024-11-29 21:47 UTC, platypii approved these changes
Thanks @cbardasano!

2024-11-29 21:48 UTC, merged

2024-11-29 22:53 UTC, platypii commented
Published v1.6.2 with this fix